version: 2.1

orbs:
  node: circleci/node@4.9.0

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
jobs:
  test:
    environment:
      VUE_APP_GITHUB_KEY: YmVmZWZmM2Q3YjZlZWEwYjgxODQ2ZjMzNjdjMGExYzdhNGY0NWIzOQ==
     
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          # Testing!
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Run Tests
          command: |
            mkdir -p ./test-results/junit
            yarn test --ci --reporters=jest-junit
      - store_artifacts:
          path: ./test-results/junit
      - store_test_results:
          path: ./test-results

workflows:
  my-custom-workflow:
    jobs:
      - test
      - node/test:
            test-results-for: jest 
            pkg-manager: yarn 
            version: '14.18.0' 
            override-ci-command: yarn 
            run-command: test:unit